---
title: "grade_analysis"
author: "by Jinane Amal"
format: html
---
```{r}
#| message: false 
here::i_am("grade_analysis.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)

```

# Question 1 
```{r}
#| message: false 
Grades <- vroom (here("grades.csv"))
```
# Question 2
```{r}
Grades|>
  summary(mean=mean(Exam,na.rm=TRUE), min=min(Exam,na.rm=TRUE), max=max(Exam,na.rm=TRUE),median=median(Exam,na.rm=TRUE)) |>
  knitr::kable()

```
# Question 3

```{r}
num_students_did_not_take_exam <- Grades |> summarize(num_students_did_not_take_exam = sum(is.na(Exam)))
```

There are `r num_students_did_not_take_exam` students who did not take the exam

# Question 4

```{r}
ggplot(Grades,aes(x=Exam)) + geom_bar()

```
# Question 5
```{r}
Grades |> 
  group_by(Group)|>
  summarise(Total= n())|>
  knitr::kable()

```

# Question 6
```{r}

group_counts <- Grades |>
  group_by(Group)|>
  summarize(Count = n())

group_bar_plot <- ggplot(group_counts, aes(x = Group, y = Count)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(
    title = "Number of Students in Each Group",
    x = "Group",
    y = "Number of Students"
  ) +
  theme_minimal()
print(group_bar_plot)

```
# Question 7 
```{r}

boxplot <- Grades |>
  ggplot(aes(x = Group, y = Exam)) +
  geom_boxplot() +
  labs(
    title = "Distribution of Exam Grades by Group (Box Plots)",
    x = "Group",
    y = "Exam Grades"
  ) +
  theme_minimal()

histogram <- Grades|>
  ggplot(aes(x = Exam)) +
  geom_histogram(binwidth = 5, fill = "blue", color = "black") +
  labs(
    title = "Distribution of Exam Grades by Group (Faceted Histograms)",
    x = "Exam Grades",
    y = "Frequency"
  ) +
  facet_wrap(~Group) +
  theme_minimal()

plot1 <- ggplotGrob(boxplot)
plot2 <- ggplotGrob(histogram)

gridExtra::grid.arrange(plot1, plot2, ncol = 2)

```
# Question 8
```{r}

missed_exam_counts <- Grades|>
  group_by(Group) |>
  summarize(Num_Missed_Exam = sum(is.na(Exam)))

missed_exam_counts

```

# Question 9
```{r}
missed_exam_counts <- missed_exam_counts |>
  arrange(Group)  
bar_chart <- ggplot(missed_exam_counts, aes(x = Group, y = Num_Missed_Exam)) +
  geom_col(fill = "blue") +
  labs(
    title = "Number of Students Who Missed the Exam by Group",
    x = "Group",
    y = "Number of Students"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(bar_chart)
```

# Question 10
```{r}
grades_data_long <- Grades |>
  pivot_longer(cols = -c(Id, Group),
               names_to = "variable",  
               values_to = "value") 
```

# Question 11
```{r}
missing_grades_summary <- grades_data_long |>
  group_by(Id)|>
  summarize(missing_grades = sum(is.na(value)))|>
  ungroup()     
missing_grades_summary
```
# Question 12 

```{r}
missing_grades_summary |>
  ggplot(aes(x = factor(Id), y = missing_grades)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_text(aes(label = missing_grades), vjust = -0.5) +
  labs(x = "Student ID", y = "Number of Missing Grades") +
  ggtitle("Distribution of Missing Grades per Student ID") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

# Question 13
```{r}
students_missed_exam <- grades_data_long |>
  filter(is.na(value) , str_starts(Group, "grp_1")) |>
  group_by(Group) |>
  summarise(num_students_missed_exam = n()) |>
  ungroup()
students_missed_exam

```
# Question 14 
```{r}
missing_online_test_grades <- grades_data_long |>
  filter(is.na(value) & grepl("Online_MCQ_", variable))|> 
  group_by(Id) |>                                           
  summarise(missing_count = sum(is.na(value))) |>
  ungroup()
missing_online_test_grades
```

# Question 15 Option 1
```{r}
grades_data <- Grades |>
  rowwise() |>
  mutate(missing_online_test_count = sum(c_across(starts_with("Online_MCQ_")))) %>%
  ungroup()
grades_data |>
  ggplot(aes(x = Exam, fill = factor(missing_online_test_count))) +
  geom_histogram(binwidth = 5) +
  labs(x = "Exam Grade", y = "Frequency") +
  ggtitle("Distribution of Exam Grades Conditioned by Missing Online Test Grades")
```

# Question 15 Option 2
```{r}
grades_data_conditional <- grades_data |>
  left_join(missing_online_test_grades, by = "Id")
grades_data_conditional |>
  ggplot(aes(x = Exam, fill = factor(missing_count))) +
  geom_histogram(binwidth = 5) +
  labs(x = "Exam Grade", y = "Frequency") +
  ggtitle("Distribution of Exam Grades Conditioned by Missing Online Test Grades")
```

# Question 16 
```{r}
missed_table <- Grades |>
  group_by(Id)|>
  summarise(Missed = any(is.na(c_across(starts_with("MCQ_")))))
missed_table
```

# Question 17

```{r}
group_missed_table <- grades_data|>
  group_by(Group)|>
  summarise(P_missed = pmin((sum(is.na(c_across(starts_with("MCQ_"))) > 0) / n()) * 100, 100))
group_missed_table
```

# Question 18 
```{r}
average_exam_grades <- Grades|>
  group_by(Group)|>
  summarise(Avg_Exam_Grade = mean(Exam, na.rm = TRUE))
combined_data <- inner_join(group_missed_table, average_exam_grades, by = "Group")
combined_data|>
  ggplot(aes(x = P_missed, y = Avg_Exam_Grade)) +
  geom_point() +
  labs(x = "Percentage of Missed MCQ Grades", y = "Average Exam Grade") +
  ggtitle("Average Exam Grade vs. Percentage of Missed MCQ Grades")

```

